development:
  server: "http://10.125.1.5/faye"
  secret_token: "eepWedgogruWaydFabrEuHacOarmyithUtVeurWecVatBasbapnahejwouHywij4"
test:
  server: "http://10.125.1.5/faye"
  secret_token: "eepWedgogruWaydFabrEuHacOarmyithUtVeurWecVatBasbapnahejwouHywij4"
production:
  server: "http://10.125.1.5/faye"
  secret_token: "eepWedgogruWaydFabrEuHacOarmyithUtVeurWecVatBasbapnahejwouHywij4"
  signature_expiration: 3600 # one hour
